### ISSUE TITLE
No such file or directory - yt-dlp (Errno::ENOENT)

### ISSUE THREAD

**Issue by Avivbens** [vitorgalvao/download-media-workflow#2]
### Workflow version

2022.5

### Alfred version

5.0.6

### macOS version

13.1

### Debugger output

```alfred_debugger
[00:59:10.735] Download Media[Script Filter] Queuing argument ''
[00:59:11.228] Download Media[Script Filter] Script with argv '' finished
[00:59:11.232] Download Media[Script Filter] {"items":[{"subtitle":"Add to WatchList (⌥): true 𐄁 Full Playlist (⌘): false","valid":true,"variables":{"media_type":"video","add_to_watchlist":true,"full_playlist":false},"mods":{"cmd":{"subtitle":"Add to WatchList (⌥): true 𐄁 Full Playlist (⌘): true","variables":{"media_type":"video","Add_to_watchlist":true,"full_playlist":true}},"alt":{"subtitle":"Add to WatchList (⌥): false 𐄁 Full Playlist (⌘): false","variables":{"media_type":"video","add_to_watchlist":false,"full_playlist":false}},"cmd+alt":{"subtitle":"Add to WatchList (⌥): false 𐄁 Full Playlist (⌘): true","variables":{"media_type":"video","add_to_watchlist":false,"full_playlist":true}}},"uid":"Download video tab","title":"(36) הופעות האורח הגדולות במפץ הגדול - YouTube","arg":"https://www.youtube.com/watch?v=9wePSk4qHAw&ab_channel=WatchMojoIsrael"},{"subtitle":"Add to WatchList (⌥): true 𐄁 Full Playlist (⌘): false","valid":true,"variables":{"media_type":"video","add_to_watchlist":true,"full_playlist":false},"mods":{"cmd":{"subtitle":"Add to WatchList (⌥): true 𐄁 Full Playlist (⌘): true","variables":{"media_type":"video","Add_to_watchlist":true,"full_playlist":true}},"alt":{"subtitle":"Add to WatchList (⌥): false 𐄁 Full Playlist (⌘): false","variables":{"media_type":"video","add_to_watchlist":false,"full_playlist":false}},"cmd+alt":{"subtitle":"Add to WatchList (⌥): false 𐄁 Full Playlist (⌘): true","variables":{"media_type":"video","add_to_watchlist":false,"full_playlist":true}}},"uid":"Download video clipboard","title":"https://www.skysilk.com/","arg":"https://www.skysilk.com/"}]}
[00:59:13.194] Download Media[Script Filter] Processing complete
[00:59:13.203] Download Media[Script Filter] Passing output 'https://www.youtube.com/watch?v=9wePSk4qHAw&ab_channel=WatchMojoIsrael' to Run Script
[00:59:13.416] ERROR: Download Media[Run Script] /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:213:in `spawn': No such file or directory - yt-dlp (Errno::ENOENT)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:213:in `popen_run'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:159:in `popen2'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open3.rb:342:in `capture2'
	from <Blur>/alfred-config/Alfred.alfredpreferences/workflows/user.workflow.0F8641AC-ECDF-4262-8C9E-D769AC79A479/downmedia_functions.rb:153:in `download_url'
	from <Blur>/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/21ACAC0A-1199-4099-9172-705A477C6C92:5:in `<main>'

```
```


### More details

I have `yt-dlp` installed on my Mac
For some reason the program just does not work

**Comment by vitorgalvao** [comment]
You have to install `yt-dlp` *with Homebrew*. It needs to be located in either `/opt/homebrew/bin` or `/usr/local/bin`. The [dependencies manager](https://www.alfredapp.com/help/kb/dependencies/) can help you install it.
